version: '3'

services:
  web:
    build: .
    container_name: online_store_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - logs:/app/logs
  db:
    image: postgres:15
    container_name: online_store_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: { }
  logs: { }
